# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'quoteListItem.ui'
##
## Created by: Qt User Interface Compiler version 6.11.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QGridLayout,
    QLabel, QLineEdit, QSizePolicy, QWidget)

class Ui_Form(object):
    def setupUi(self, Form):
        if not Form.objectName():
            Form.setObjectName(u"Form")
        Form.resize(596, 230)
        Form.setMinimumSize(QSize(591, 230))
        self.label_ID = QLabel(Form)
        self.label_ID.setObjectName(u"label_ID")
        self.label_ID.setGeometry(QRect(0, 30, 71, 61))
        font = QFont()
        font.setPointSize(28)
        self.label_ID.setFont(font)
        self.label_ID.setStyleSheet(u"color:rgb(120, 120, 120)")
        self.label_ID.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.unitLb = QLabel(Form)
        self.unitLb.setObjectName(u"unitLb")
        self.unitLb.setGeometry(QRect(10, 140, 41, 31))
        font1 = QFont()
        font1.setPointSize(12)
        self.unitLb.setFont(font1)
        self.unitLb.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.itemTypeLb = QLabel(Form)
        self.itemTypeLb.setObjectName(u"itemTypeLb")
        self.itemTypeLb.setGeometry(QRect(90, 20, 81, 21))
        font2 = QFont()
        font2.setPointSize(11)
        font2.setBold(True)
        self.itemTypeLb.setFont(font2)
        self.itemTypeLb.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.layoutWidget = QWidget(Form)
        self.layoutWidget.setObjectName(u"layoutWidget")
        self.layoutWidget.setGeometry(QRect(330, 0, 251, 56))
        self.gridLayout = QGridLayout(self.layoutWidget)
        self.gridLayout.setObjectName(u"gridLayout")
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.metroCheckBox = QCheckBox(self.layoutWidget)
        self.metroCheckBox.setObjectName(u"metroCheckBox")
        self.metroCheckBox.setFocusPolicy(Qt.FocusPolicy.NoFocus)
        self.metroCheckBox.setCheckable(True)

        self.gridLayout.addWidget(self.metroCheckBox, 0, 0, 1, 1)

        self.highPresCheckBox = QCheckBox(self.layoutWidget)
        self.highPresCheckBox.setObjectName(u"highPresCheckBox")
        self.highPresCheckBox.setFocusPolicy(Qt.FocusPolicy.NoFocus)
        self.highPresCheckBox.setToolTipDuration(5000)
        self.highPresCheckBox.setCheckable(True)

        self.gridLayout.addWidget(self.highPresCheckBox, 0, 1, 1, 1)

        self.exCheckBox = QCheckBox(self.layoutWidget)
        self.exCheckBox.setObjectName(u"exCheckBox")
        self.exCheckBox.setFocusPolicy(Qt.FocusPolicy.NoFocus)
        self.exCheckBox.setToolTipDuration(5000)
        self.exCheckBox.setCheckable(True)

        self.gridLayout.addWidget(self.exCheckBox, 1, 0, 1, 1)

        self.digiCheckBox = QCheckBox(self.layoutWidget)
        self.digiCheckBox.setObjectName(u"digiCheckBox")
        self.digiCheckBox.setFocusPolicy(Qt.FocusPolicy.NoFocus)
        self.digiCheckBox.setToolTipDuration(5000)
        self.digiCheckBox.setCheckable(True)

        self.gridLayout.addWidget(self.digiCheckBox, 1, 1, 1, 1)

        self.qtyBox = QLineEdit(Form)
        self.qtyBox.setObjectName(u"qtyBox")
        self.qtyBox.setGeometry(QRect(10, 110, 41, 31))
        font3 = QFont()
        font3.setPointSize(15)
        self.qtyBox.setFont(font3)
        self.qtyBox.setReadOnly(False)
        self.productLb = QLabel(Form)
        self.productLb.setObjectName(u"productLb")
        self.productLb.setGeometry(QRect(80, 60, 61, 21))
        self.productLb.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.sensorLb = QLabel(Form)
        self.sensorLb.setObjectName(u"sensorLb")
        self.sensorLb.setGeometry(QRect(60, 90, 81, 21))
        self.sensorLb.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.jBoxLb = QLabel(Form)
        self.jBoxLb.setObjectName(u"jBoxLb")
        self.jBoxLb.setGeometry(QRect(60, 120, 81, 21))
        self.jBoxLb.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.controllerLb = QLabel(Form)
        self.controllerLb.setObjectName(u"controllerLb")
        self.controllerLb.setGeometry(QRect(60, 150, 81, 21))
        self.controllerLb.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.controllerLb_2 = QLabel(Form)
        self.controllerLb_2.setObjectName(u"controllerLb_2")
        self.controllerLb_2.setGeometry(QRect(260, 120, 61, 21))
        self.controllerLb_2.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.accessoryLb_1 = QLabel(Form)
        self.accessoryLb_1.setObjectName(u"accessoryLb_1")
        self.accessoryLb_1.setGeometry(QRect(410, 120, 51, 21))
        self.accessoryLb_1.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.accessoryLb_2 = QLabel(Form)
        self.accessoryLb_2.setObjectName(u"accessoryLb_2")
        self.accessoryLb_2.setGeometry(QRect(410, 150, 51, 21))
        self.accessoryLb_2.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.accessoryLb_3 = QLabel(Form)
        self.accessoryLb_3.setObjectName(u"accessoryLb_3")
        self.accessoryLb_3.setGeometry(QRect(410, 180, 51, 21))
        self.accessoryLb_3.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.comboBox = QComboBox(Form)
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.setObjectName(u"comboBox")
        self.comboBox.setGeometry(QRect(170, 20, 121, 21))
        self.comboBox.setToolTipDuration(5000)
        self.comboBox.setAutoFillBackground(True)
        self.comboBox.setEditable(True)
        self.sensorComBox = QComboBox(Form)
        self.sensorComBox.setObjectName(u"sensorComBox")
        self.sensorComBox.setGeometry(QRect(140, 90, 221, 21))
        self.sensorComBox.setToolTipDuration(5000)
        self.sensorComBox.setAutoFillBackground(True)
        self.sensorComBox.setEditable(True)
        self.jBoxComBox = QComboBox(Form)
        self.jBoxComBox.setObjectName(u"jBoxComBox")
        self.jBoxComBox.setGeometry(QRect(140, 120, 111, 21))
        self.jBoxComBox.setToolTipDuration(5000)
        self.jBoxComBox.setAutoFillBackground(True)
        self.jBoxComBox.setEditable(True)
        self.controllerComboBox_1 = QComboBox(Form)
        self.controllerComboBox_1.setObjectName(u"controllerComboBox_1")
        self.controllerComboBox_1.setGeometry(QRect(140, 150, 221, 21))
        self.controllerComboBox_1.setToolTipDuration(5000)
        self.controllerComboBox_1.setAutoFillBackground(True)
        self.controllerComboBox_1.setEditable(True)
        self.controllerComBox_2 = QComboBox(Form)
        self.controllerComBox_2.setObjectName(u"controllerComBox_2")
        self.controllerComBox_2.setGeometry(QRect(320, 120, 91, 21))
        self.controllerComBox_2.setToolTipDuration(5000)
        self.controllerComBox_2.setAutoFillBackground(True)
        self.controllerComBox_2.setEditable(True)
        self.accessoryComBox_1 = QComboBox(Form)
        self.accessoryComBox_1.setObjectName(u"accessoryComBox_1")
        self.accessoryComBox_1.setGeometry(QRect(460, 120, 121, 21))
        self.accessoryComBox_1.setToolTipDuration(5000)
        self.accessoryComBox_1.setAutoFillBackground(True)
        self.accessoryComBox_1.setEditable(True)
        self.accessoryComBox_2 = QComboBox(Form)
        self.accessoryComBox_2.setObjectName(u"accessoryComBox_2")
        self.accessoryComBox_2.setGeometry(QRect(460, 150, 121, 21))
        self.accessoryComBox_2.setToolTipDuration(5000)
        self.accessoryComBox_2.setAutoFillBackground(True)
        self.accessoryComBox_2.setEditable(True)
        self.accessoryComBox_3 = QComboBox(Form)
        self.accessoryComBox_3.setObjectName(u"accessoryComBox_3")
        self.accessoryComBox_3.setGeometry(QRect(460, 180, 121, 21))
        self.accessoryComBox_3.setToolTipDuration(5000)
        self.accessoryComBox_3.setAutoFillBackground(True)
        self.accessoryComBox_3.setEditable(True)
        self.derivativeLb = QLabel(Form)
        self.derivativeLb.setObjectName(u"derivativeLb")
        self.derivativeLb.setGeometry(QRect(400, 90, 61, 21))
        self.derivativeLb.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.derivativeComBox = QComboBox(Form)
        self.derivativeComBox.setObjectName(u"derivativeComBox")
        self.derivativeComBox.setGeometry(QRect(460, 90, 121, 21))
        self.derivativeComBox.setToolTipDuration(5000)
        self.derivativeComBox.setAutoFillBackground(True)
        self.derivativeComBox.setEditable(False)
        self.displayLb = QLabel(Form)
        self.displayLb.setObjectName(u"displayLb")
        self.displayLb.setGeometry(QRect(70, 180, 74, 21))
        self.displayLb.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.displayEdit = QLineEdit(Form)
        self.displayEdit.setObjectName(u"displayEdit")
        self.displayEdit.setGeometry(QRect(140, 180, 121, 21))
        self.displayEdit.setToolTipDuration(5000)
        self.displayEdit.setReadOnly(True)
        self.productComBox = QComboBox(Form)
        self.productComBox.setObjectName(u"productComBox")
        self.productComBox.setGeometry(QRect(140, 60, 311, 21))

        self.retranslateUi(Form)

        QMetaObject.connectSlotsByName(Form)
    # setupUi

    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", u"list", None))
        self.label_ID.setText(QCoreApplication.translate("Form", u"ID", None))
        self.unitLb.setText(QCoreApplication.translate("Form", u"\u5957", None))
        self.itemTypeLb.setText(QCoreApplication.translate("Form", u"\u6761\u76ee\u7c7b\u578b\uff1a", None))
        self.metroCheckBox.setText(QCoreApplication.translate("Form", u"\u662f\u5426\u9700\u8981\u68c0\u5b9a", None))
#if QT_CONFIG(tooltip)
        self.highPresCheckBox.setToolTip(QCoreApplication.translate("Form", u"\u6ce8\u610f\uff1a\u6c7d\u8f66\u8861\u7684\u9ad8\u7cbe\u5ea6\u4e3aC4\u7b49\u7ea7\u3002", None))
#endif // QT_CONFIG(tooltip)
        self.highPresCheckBox.setText(QCoreApplication.translate("Form", u"\u662f\u5426\u9ad8\u7cbe\u5ea6", None))
#if QT_CONFIG(tooltip)
        self.exCheckBox.setToolTip(QCoreApplication.translate("Form", u"\u5982\u52fe\u9009\uff0c\u8bf7\u5728\u4e0b\u65b9\u8f93\u5165\u5177\u4f53\u7684\u9632\u7206\u7b49\u7ea7\u3002\u9ed8\u8ba4\u4e3aIIBT4\u3002", None))
#endif // QT_CONFIG(tooltip)
        self.exCheckBox.setText(QCoreApplication.translate("Form", u"\u662f\u5426\u9632\u7206", None))
#if QT_CONFIG(tooltip)
        self.digiCheckBox.setToolTip(QCoreApplication.translate("Form", u"\u672a\u5b8c\u5584,\u9700\u4eba\u5de5\u590d\u67e5", None))
#endif // QT_CONFIG(tooltip)
        self.digiCheckBox.setText(QCoreApplication.translate("Form", u"\u6570\u5b57\u5316\u65b9\u6848", None))
        self.productLb.setText(QCoreApplication.translate("Form", u"\u6a21\u5757\u578b\u53f7\uff1a", None))
        self.sensorLb.setText(QCoreApplication.translate("Form", u"\u4f20\u611f\u5668\u578b\u53f7\uff1a", None))
        self.jBoxLb.setText(QCoreApplication.translate("Form", u"\u63a5\u7ebf\u76d2\u578b\u53f7\uff1a", None))
        self.controllerLb.setText(QCoreApplication.translate("Form", u"\u4eea\u8868\u578b\u53f7\uff1a", None))
        self.controllerLb_2.setText(QCoreApplication.translate("Form", u"\u4eea\u8868\u5b89\u88c5\uff1a", None))
        self.accessoryLb_1.setText(QCoreApplication.translate("Form", u"\u9644\u4ef61\uff1a", None))
        self.accessoryLb_2.setText(QCoreApplication.translate("Form", u"\u9644\u4ef62\uff1a", None))
        self.accessoryLb_3.setText(QCoreApplication.translate("Form", u"\u9644\u4ef63\uff1a", None))
        self.comboBox.setItemText(0, QCoreApplication.translate("Form", u"\u79f0\u91cd\u6a21\u5757", None))
        self.comboBox.setItemText(1, QCoreApplication.translate("Form", u"\u5e73\u53f0\u79e4", None))
        self.comboBox.setItemText(2, QCoreApplication.translate("Form", u"\u53f0\u79e4", None))
        self.comboBox.setItemText(3, QCoreApplication.translate("Form", u"\u6c7d\u8f66\u8861", None))
        self.comboBox.setItemText(4, QCoreApplication.translate("Form", u"\u6570\u5b57\u6c7d\u8f66\u8861", None))

#if QT_CONFIG(tooltip)
        self.comboBox.setToolTip(QCoreApplication.translate("Form", u"<html><head/><body><p>\u9f20\u6807\u60ac\u505c\u5e76\u6eda\u52a8\u6eda\u8f6e\u53ef\u5feb\u901f\u5207\u6362\u3002</p><p>\u6253\u5b57\u53ef\u8865\u5168\u3002</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.comboBox.setPlaceholderText(QCoreApplication.translate("Form", u"\u8bf7\u9009\u62e9\u6761\u76ee\u7c7b\u578b", None))
#if QT_CONFIG(tooltip)
        self.sensorComBox.setToolTip(QCoreApplication.translate("Form", u"<html><head/><body><p>\u9f20\u6807\u60ac\u505c\u5e76\u6eda\u52a8\u6eda\u8f6e\u53ef\u5feb\u901f\u5207\u6362\u3002</p><p>\u6253\u5b57\u53ef\u8865\u5168\u3002</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.sensorComBox.setPlaceholderText(QCoreApplication.translate("Form", u"\u8bf7\u9009\u62e9\u6761\u76ee\u7c7b\u578b", None))
#if QT_CONFIG(tooltip)
        self.jBoxComBox.setToolTip(QCoreApplication.translate("Form", u"<html><head/><body><p>\u9f20\u6807\u60ac\u505c\u5e76\u6eda\u52a8\u6eda\u8f6e\u53ef\u5feb\u901f\u5207\u6362\u3002</p><p>\u6253\u5b57\u53ef\u8865\u5168\u3002</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.jBoxComBox.setPlaceholderText(QCoreApplication.translate("Form", u"\u8bf7\u9009\u62e9\u6761\u76ee\u7c7b\u578b", None))
#if QT_CONFIG(tooltip)
        self.controllerComboBox_1.setToolTip(QCoreApplication.translate("Form", u"<html><head/><body><p>\u9f20\u6807\u60ac\u505c\u5e76\u6eda\u52a8\u6eda\u8f6e\u53ef\u5feb\u901f\u5207\u6362\u3002</p><p>\u6253\u5b57\u53ef\u8865\u5168\u3002</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.controllerComboBox_1.setPlaceholderText(QCoreApplication.translate("Form", u"\u8bf7\u9009\u62e9\u6761\u76ee\u7c7b\u578b", None))
#if QT_CONFIG(tooltip)
        self.controllerComBox_2.setToolTip(QCoreApplication.translate("Form", u"<html><head/><body><p>\u9f20\u6807\u60ac\u505c\u5e76\u6eda\u52a8\u6eda\u8f6e\u53ef\u5feb\u901f\u5207\u6362\u3002</p><p>\u6253\u5b57\u53ef\u8865\u5168\u3002</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.controllerComBox_2.setPlaceholderText(QCoreApplication.translate("Form", u"\u8bf7\u9009\u62e9\u6761\u76ee\u7c7b\u578b", None))
#if QT_CONFIG(tooltip)
        self.accessoryComBox_1.setToolTip(QCoreApplication.translate("Form", u"<html><head/><body><p>\u9f20\u6807\u60ac\u505c\u5e76\u6eda\u52a8\u6eda\u8f6e\u53ef\u5feb\u901f\u5207\u6362\u3002</p><p>\u6253\u5b57\u53ef\u8865\u5168\u3002</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.accessoryComBox_1.setPlaceholderText(QCoreApplication.translate("Form", u"\u8bf7\u9009\u62e9\u6761\u76ee\u7c7b\u578b", None))
#if QT_CONFIG(tooltip)
        self.accessoryComBox_2.setToolTip(QCoreApplication.translate("Form", u"<html><head/><body><p>\u9f20\u6807\u60ac\u505c\u5e76\u6eda\u52a8\u6eda\u8f6e\u53ef\u5feb\u901f\u5207\u6362\u3002</p><p>\u6253\u5b57\u53ef\u8865\u5168\u3002</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.accessoryComBox_2.setPlaceholderText(QCoreApplication.translate("Form", u"\u8bf7\u9009\u62e9\u6761\u76ee\u7c7b\u578b", None))
#if QT_CONFIG(tooltip)
        self.accessoryComBox_3.setToolTip(QCoreApplication.translate("Form", u"<html><head/><body><p>\u9f20\u6807\u60ac\u505c\u5e76\u6eda\u52a8\u6eda\u8f6e\u53ef\u5feb\u901f\u5207\u6362\u3002</p><p>\u6253\u5b57\u53ef\u8865\u5168\u3002</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.accessoryComBox_3.setPlaceholderText(QCoreApplication.translate("Form", u"\u8bf7\u9009\u62e9\u6761\u76ee\u7c7b\u578b", None))
        self.derivativeLb.setText(QCoreApplication.translate("Form", u"\u884d\u751f\u54c1\u79cd\uff1a", None))
#if QT_CONFIG(tooltip)
        self.derivativeComBox.setToolTip(QCoreApplication.translate("Form", u"\u9009\u62e9\u884d\u751f\u54c1\u79cd\u540e\u81ea\u52a8\u89e3\u6790\u884d\u751f\u578b\u53f7\uff0c\u8f93\u51fa\u62a5\u4ef7\u65f6\u4ee5\u884d\u751f\u578b\u53f7\u66ff\u6362\u4ea7\u54c1\u578b\u53f7\uff1b\u4f20\u611f\u5668\u7b49\u5176\u4f59\u9009\u578b\u4e0d\u53d7\u5f71\u54cd\u3002", None))
#endif // QT_CONFIG(tooltip)
        self.derivativeComBox.setPlaceholderText(QCoreApplication.translate("Form", u"\u6807\u51c6\u578b", None))
        self.displayLb.setText(QCoreApplication.translate("Form", u"\u5927\u5c4f\u5e55\u578b\u53f7\uff1a", None))
#if QT_CONFIG(tooltip)
        self.displayEdit.setToolTip(QCoreApplication.translate("Form", u"\u9009\u62e9\u5927\u5c4f\u5e55/\u9632\u7206\u5927\u5c4f\u5e55\u9644\u4ef6\u5e76\u5728\u5b50\u5bf9\u8bdd\u6846\u786e\u8ba4\u9009\u578b\u540e\u663e\u793a\uff1b\u8f93\u51fa\u62a5\u4ef7\u65f6\u6309\u6b64\u578b\u53f7\u843d\u884c\u3002", None))
#endif // QT_CONFIG(tooltip)
        self.displayEdit.setPlaceholderText(QCoreApplication.translate("Form", u"\u672a\u9009", None))
    # retranslateUi

